name = "high-bandwidth-recognition-benchmarks"
keywords = ["matrix bandwidth", "graph algorithms", "benchmarking"]
license = "MIT"
authors = ["Luis M. B. Varona <lm.varona@outlook.com>"]
description = "Companion code for the paper \"A polynomial-time algorithm for recognizing high-bandwidth graphs\"."
maintainers = ["Luis M. B. Varona <lm.varona@outlook.com>"]
readme = "README.md"
repository = "https://github.com/Luis-Varona/high-bandwidth-recognition-benchmarks"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MatrixBandwidth = "075aa41b-24fd-4573-b25f-92cae432c0f8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
BenchmarkTools = "1.5"
CSV = "0.10"
Combinatorics = "1.0"
DataFrames = "1.7"
Dates = "1.10"
MatrixBandwidth = "0.3"
Random = "1.10"
Serialization = "1.10"
julia = "1.10"
